# Builder
FROM node:18 AS builder

WORKDIR /app

# Build Phase
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Runner
FROM node:18
RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app
COPY package*.json ./
RUN npm install --only=production
COPY --from=builder /app/dist ./dist

# Expose port 3000
EXPOSE 3000
CMD ["npm", "run", "serve"]