# Base Image
FROM node:18

# Define work directory
WORKDIR /app

# Dependency install - FFMPEG
RUN apt-get update && apt-get install -y ffmpeg

# Copy package.json and package-lock.json into the working directory 
COPY package*.json ./
RUN npm install

# Get service source code
COPY . .
# Expose port 3000
EXPOSE 3000
CMD ["npm", "start"]

